apiVersion: v1
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: cm-sqs
  namespace: 3htp
data:
  application.properties: |
    app.queue.name=IAMRoleEKS-q-DEV-in
    app.queue.out.name=IAMRoleEKS-q-DEV-out.fifo
    app.use-role-type=WebIdentityTokenCredentialsProvider